[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "panoptes_aggregation"
description = "Aggregation code for Zooniverse panoptes projects."
authors = [
    {name = "Coleman Krawczyk", email = "coleman@zooniverse.org"},
]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License"
]
dynamic = ["version"]
requires-python = ">=3.7,<3.11"
dependencies = [
    "beautifulsoup4>=4.8.1,<4.13",
    "collatex>=2.2,<2.3",
    "hdbscan>=0.8.20,<=0.8.33",
    "lxml>=4.4,<4.10",
    "numpy>=1.22.0,<1.25.2",
    "packaging>=20.1,<23.1",
    "pandas>=1.0.0,<1.5.4",
    "progressbar2>=3.39,<4.3",
    "python-levenshtein>=0.12.0,<0.21",
    "python-slugify>=3.0.0,<8.1",
    "pyyaml>=5.1,<6.1",
    "scikit-learn>=1.0.0,<1.2.3",
    "scipy>=1.6.1,<1.10.2",
    "werkzeug>=0.14,<2.3.5",
    "shapely>=1.7.1,<2.0.2"
]

[project.optional-dependencies]
online = [
    "flask>=2.0,<2.3",
    "flask-cors>=3.0,<3.1",
    "panoptes-client>=1.1,<1.7",
    "requests>=2.4.2,<2.31",
    "gunicorn>=20.0,<20.2",
    "sentry-sdk[flask]>=0.13.5,<1.25",
    "newrelic>=5.4.0,<8.8.1",
    "gitpython>=3.0.0,<3.2"
]
gui = [
    "Gooey>=1.0.8.1,<1.1"
]
doc = [
    "matplotlib>=3.5.1,<3.8",
    "myst-nb>=0.13.2,<0.18",
    "sphinx>=2.2.2,<6.2",
    "sphinxcontrib-httpdomain>=1.7.0,<1.9",
    "sphinx_rtd_theme>=0.4.3,<1.3"
]
test = [
    "coverage>=4.5.3,<7.3",
    "coveralls>=3.0.0,<3.3.2",
    "flake8>=3.7,<6.1",
    "flake8-black>=0.1.1,<0.4",
    "flake8-bugbear>=20.1.2,<23.3",
    "pytest>=7.1.2,<7.4.2",
    "pytest-subtests>=0.8.0,<0.11.1"
]

[project.scripts]
panoptes_aggregation = "panoptes_aggregation.scripts.aggregation_parser:main"

[project.gui-scripts]
panoptes_aggregation_gui = "panoptes_aggregation.scripts.gui:gui"

[project.urls]
Documentation = "https://aggregation-caesar.zooniverse.org/docs"
Source = "https://github.com/zooniverse/aggregation-for-caesar"

[tool.flit.sdist]
include = [
    "panoptes_aggregation/scripts/icons/*",
    "LICENSE"
]
exclude = [
    "docs/",
    "kubernetes",
    "make_docs.sh"
]

[tool.coverage.run]
omit = [
    "*test*",
    "panoptes_aggregation/scripts/gui*.py",
    "panoptes_aggregation/scripts/no_gooey.py",
    "panoptes_aggregation/scripts/path_type.py"
]
source = ["panoptes_aggregation"]
command_line = "-m pytest"

[tool.coverage.report]
show_missing = true
