name: Python tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
    - name: Install panoptes aggregation
      run: |
        pip install -U pip
        pip install -U .[online,test,doc]
    - name: Run tests
      env:
        TRAVIS: true  # one test is skipped on CI and looks for this env value
      run: |
        coverage run
        coverage report
    - name: Coveralls
      if: ${{ matrix.python-version == 3.10 }}
      env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github
